export default [
  {
    id: 1,
    postedOn: "2023-12-29",
    title: "Ios Developer",
    company: "Apple",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["SwiftUI", "UiKit", "Core Data"],
    job_Link: "https://www.apple.com/careers/in/",
  },
  {
    id: 2,
    postedOn: "2023-12-29",
    title: "Frontend Developer",
    company: "Amazon",
    type: "Full Time",
    experience: "Fresher",
    location: "In-office",
    skills: ["Javascript", "Nextjs", "Tailwind CSS"],
    job_Link: "https://www.amazon.jobs/en/",
  },
  {
    id: 3,
    postedOn: "2023-12-29",
    title: "Full-stack Developer",
    company: "steam",
    type: "Full Time",
    experience: "Junior level",
    location: "Hybrid",
    skills: ["Reactjs", "Nodejs", "tailwind", "mongoDB", "Express"],
    job_Link: "https://www.valvesoftware.com/en/jobs?job_id=14",
  },
  {
    id: 4,
    postedOn: "2023-12-29",
    title: "web developer",
    company: "TCS",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["html5", "css3", "javascript", "jquery", "scss"],
    job_Link: "https://www.tcs.com/careers",
  },
];
